{"errorMessage": "type object 'datetime.datetime' has no attribute 'timezone'", "errorType": "AttributeError", "stackTrace": ["  File \"/var/task/create_task.py\", line 12, in lambda_handler\n    timestamp = datetime.now(datetime.timezone.utc).isoformat()\n"]}